apiVersion: apps/v1beta1
kind: Deployment
metadata:
  
  name: deployment-example
spec:
  
  replicas: 3
  template:
    metadata:
      labels:
        
        app: drupal
    spec:
      containers:
      - name: drupal
       
        image: drupal
